name: eschool
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.2.7+9

environment:
  sdk: ">=3.0.2 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #External packages
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  dotted_border: ^2.1.0
  table_calendar: ^3.1.2
  win32: ^5.4.0
  dio: ^5.4.3+1
  lottie: ^3.1.2
  showcaseview: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  path_provider: ^2.1.3
  url_launcher: ^6.3.0
  youtube_player_flutter: ^9.0.1
  video_player: ^2.8.7
  file_picker: ^8.0.5
  permission_handler: ^11.3.1
  timeago: ^3.6.1
  firebase_messaging: ^15.0.1
  firebase_core: ^3.6.0
  awesome_notifications: ^0.10.0
  carousel_slider: ^5.0.0
  flutter_html: ^3.0.0-beta.2
  package_info_plus: ^8.0.0
  open_filex: ^4.4.0
  razorpay_flutter: ^1.3.7
  flutter_stripe: ^11.2.0
  flutter_tex: ^4.0.6
  wakelock_plus: ^1.2.5
  external_path: ^2.0.1
  flutter_animate: ^4.5.0
  flutter_inappwebview: ^6.0.0
  shared_preferences: ^2.2.3
  flutter_pdfview: ^1.3.2
  readmore: ^3.0.0
  image_picker: ^1.1.2
  any_link_preview: ^3.0.2
  flutter_keyboard_visibility: ^6.0.0
  flutter_paystack: ^1.0.7
  flutter_emoji_feedback: ^0.4.0
  #screen_protector: ^1.4.2+1

dependency_overrides:
  http: any
  intl: any
  flutter_paystack:
    git:
      url: https://github.com/I-driod/flutter_paystack.git
      ref: master
  webview_flutter_android: 3.16.1

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appLogo.png"
  remove_alpha_ios: true



flutter:


  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - google_fonts/
    - assets/languages/
    - assets/animations/
